services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  web:
    build: 
      context: ./django
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      APP_TYPE: public
    depends_on:
      - db

  api:
    build: 
      context: ./django
      dockerfile: Dockerfile.api
    ports:
      - "8001:8001"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      APP_TYPE: api
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
      - api
