FROM python:latest

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ./django .

RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x ./run-api.sh

EXPOSE 8001

CMD ["./run-api.sh"]