# Use the official Python image
FROM python:latest

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project files
COPY . .

# Expose the port the frontend will run on
EXPOSE 8000

# Command to run the frontend app using gunicorn
ENTRYPOINT ["bash","run.sh"]